services:
  docling-inference:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 8080:8080
    environment:
      - DEV_MODE=1
      - AUTH_TOKEN=dev-key
      - LOG_LEVEL=DEBUG
      - CACHE_BUCKET=
      - TRANSFORMERS_CACHE=/root/.cache/huggingface
      - EASYOCR_CACHE=/root/.EasyOCR
    volumes:
      - ./logs:/app/logs
      - ./src:/app/src:ro
      - hf_cache:/root/.cache/huggingface
      - ocr_cache:/root/.EasyOCR
    restart: always

volumes:
  hf_cache:
  ocr_cache:
